language: php

sudo: false

git:
  depth: 1

branches:
  only: 
    - master

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - if php -r "exit( (int) !version_compare( '$TRAVIS_PHP_VERSION', '5.6', '>=' ) );"; then wget -O phpunit https://phar.phpunit.de/phpunit-5.7.phar && chmod +x phpunit && mkdir ~/bin && mv -v phpunit ~/bin; fi

before_script:
  - composer --dev install

script: phpunit
